# Generated by Django 6.0.5 on 2026-05-12 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('processed_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transcription.audiorecord')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, max_length=200)),
                ('chief_complaint', models.TextField(blank=True)),
                ('history', models.TextField(blank=True)),
                ('examination', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('prescription', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('follow_up', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transcript', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transcription.transcript')),
            ],
        ),
    ]
