# Generated by Django 4.2.21 on 2026-05-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation_json', models.JSONField(blank=True, default=list)),
                ('chief_complaint', models.TextField(blank=True, default='')),
                ('present_illness', models.TextField(blank=True, default='')),
                ('diagnosis', models.TextField(blank=True, default='')),
                ('prescription', models.TextField(blank=True, default='')),
                ('treatment_plan', models.TextField(blank=True, default='')),
                ('follow_up', models.TextField(blank=True, default='')),
                ('vitals', models.TextField(blank=True, default='')),
                ('past_medical_history', models.TextField(blank=True, default='')),
            ],
        ),
    ]
