# Generated by Django 4.2.21 on 2026-05-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0002_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='patient_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
