# Generated by Django 6.0.5 on 2026-05-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0003_transcription_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='patient_age',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='transcription',
            name='patient_contact',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='transcription',
            name='patient_gender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
