# Generated by Django 6.0.5 on 2026-05-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0004_transcription_patient_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaldocument',
            name='patient_age',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='clinicaldocument',
            name='patient_contact',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='clinicaldocument',
            name='patient_gender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
