import io
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph, Spacer, Table, TableStyle,
    HRFlowable, BaseDocTemplate, PageTemplate, Frame
)
from reportlab.lib.enums import TA_CENTER
from django.http import HttpResponse

# Colors
DEEP_NAVY  = colors.HexColor('#0a1628')
TEAL       = colors.HexColor('#0d9488')
TEAL_LIGHT = colors.HexColor('#14b8a6')
GOLD       = colors.HexColor('#d4af37')
WHITE      = colors.white
MID_GRAY   = colors.HexColor('#94a3b8')


def _draw_background(c, doc):
    w, h = A4
    c.setFillColor(DEEP_NAVY);  c.rect(0, 0, w, h, fill=1, stroke=0)
    c.setFillColor(GOLD);       c.rect(0, h-18*mm, w, 18*mm, fill=1, stroke=0)
    c.setFillColor(TEAL);       c.rect(0, h-22*mm, w, 4*mm,  fill=1, stroke=0)
    c.setFillColor(TEAL);       c.rect(0, 0, w, 10*mm, fill=1, stroke=0)
    c.setFillColor(GOLD);       c.rect(0, 9*mm, w, 1.5*mm, fill=1, stroke=0)

    c.setFillColor(TEAL_LIGHT); c.setFillAlpha(0.10)
    c.rect(0, 10*mm, 7*mm, h-32*mm, fill=1, stroke=0)
    c.setFillAlpha(1)

    c.setFillColor(WHITE); c.setFillAlpha(0.025)
    for x in range(20, int(w), 18):
        for y in range(20, int(h), 18):
            c.circle(x, y, 1, fill=1, stroke=0)
    c.setFillAlpha(1)

    # Left: DocAI branding
    c.setFillColor(DEEP_NAVY)
    c.setFont("Helvetica-Bold", 22)
    c.drawString(18*mm, h-13*mm, "DocAI")
    c.setFont("Helvetica", 8)
    c.drawString(18*mm, h-17*mm, "AI-Powered Medical Documentation")

    # Right: Doctor name (stored on doc template)
    doctor_name = getattr(doc, 'doctor_name', 'Doctor')
    c.setFont("Helvetica-Bold", 13)
    c.drawRightString(w-18*mm, h-10*mm, doctor_name.upper())
    c.setFont("Helvetica", 8)
    c.drawRightString(w-18*mm, h-15*mm, "Attending Physician")

    # Footer
    c.setFont("Helvetica", 7)
    c.drawString(18*mm, 3.5*mm, "Generated by DocAI - AI-Powered Medical Transcription")
    c.drawRightString(w-18*mm, 3.5*mm, f"Page {doc.page}")


class PremiumDocTemplate(BaseDocTemplate):
    def __init__(self, buffer, doctor_name="Doctor", **kwargs):
        super().__init__(buffer, **kwargs)
        self.doctor_name = doctor_name
        frame = Frame(
            18*mm, 13*mm,
            A4[0]-36*mm, A4[1]-38*mm,
            leftPadding=0, rightPadding=0,
            topPadding=0, bottomPadding=0,
        )
        self.addPageTemplates([PageTemplate(
            id='premium', frames=[frame], onPage=_draw_background
        )])


def _styles():
    return {
        'patient_name': ParagraphStyle('PN',
            fontSize=24, fontName='Helvetica-Bold',
            textColor=GOLD, spaceAfter=2, leading=28),
        'patient_meta': ParagraphStyle('PM',
            fontSize=9, fontName='Helvetica',
            textColor=MID_GRAY, spaceAfter=0),
        'section_heading': ParagraphStyle('SH',
            fontSize=9, fontName='Helvetica-Bold',
            textColor=TEAL_LIGHT, spaceBefore=8, spaceAfter=5),
        'label': ParagraphStyle('LB',
            fontSize=8, fontName='Helvetica-Bold', textColor=GOLD),
        'value': ParagraphStyle('VL',
            fontSize=10, fontName='Helvetica',
            textColor=WHITE, leading=14),
        'not_mentioned': ParagraphStyle('NM',
            fontSize=9, fontName='Helvetica-Oblique',
            textColor=colors.HexColor('#475569')),
        'disclaimer': ParagraphStyle('DS',
            fontSize=7, fontName='Helvetica-Oblique',
            textColor=colors.HexColor('#334155'), alignment=TA_CENTER),
    }


def _val(value, s):
    if value and value.strip() and value.strip().lower() != "not mentioned":
        return Paragraph(value, s['value'])
    return Paragraph("Not mentioned", s['not_mentioned'])


def _build_premium_pdf(buffer, patient_name, record_id, created_at, fields, doctor_name="Doctor"):
    doc = PremiumDocTemplate(
        buffer,
        doctor_name=doctor_name,
        pagesize=A4,
        rightMargin=18*mm, leftMargin=18*mm,
        topMargin=26*mm, bottomMargin=15*mm,
    )
    s = _styles()
    W = A4[0] - 36*mm
    col_l, col_v = 42*mm, W - 42*mm
    story = []

    # Patient header
    story.append(Spacer(1, 3*mm))
    story.append(Paragraph(patient_name.upper(), s['patient_name']))
    story.append(Paragraph(
        f"Record #: <b>{record_id:05d}</b> &nbsp;|&nbsp; "
        f"Date: <b>{created_at.strftime('%d %B %Y')}</b> &nbsp;|&nbsp; "
        f"Time: <b>{created_at.strftime('%H:%M')}</b>",
        s['patient_meta'],
    ))
    story.append(Spacer(1, 3*mm))
    story.append(HRFlowable(width="100%", thickness=1.5, color=GOLD, spaceAfter=5))
    story.append(Paragraph("CLINICAL SUMMARY", s['section_heading']))
    story.append(Spacer(1, 2*mm))

    # Build rows — truncate long values to prevent LayoutError
    rows = []
    for label, value in fields.items():
        safe = value[:600] + '...' if value and len(value) > 600 else value
        rows.append([Paragraph(label.upper(), s['label']), _val(safe, s)])

    tbl = Table(rows, colWidths=[col_l, col_v])
    tbl.setStyle(TableStyle([
        ('VALIGN',         (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING',     (0, 0), (-1, -1), 9),
        ('BOTTOMPADDING',  (0, 0), (-1, -1), 9),
        ('LEFTPADDING',    (0, 0), (-1, -1), 10),
        ('RIGHTPADDING',   (0, 0), (-1, -1), 10),
        ('LINEAFTER',      (0, 0), (0, -1), 2, TEAL),
        ('LINEBELOW',      (0, 0), (-1, -2), 0.4, colors.HexColor('#1e3a5f')),
        ('BOX',            (0, 0), (-1, -1), 0.8, TEAL_LIGHT),
        ('LINEABOVE',      (0, 0), (-1, 0), 1.5, GOLD),
        ('LINEBELOW',      (0, -1), (-1, -1), 1.5, GOLD),
        ('BACKGROUND',     (0, 0), (0, -1), colors.HexColor('#0d1f3c')),
        ('ROWBACKGROUNDS', (1, 0), (1, -1), [
            colors.HexColor('#0f2447'),
            colors.HexColor('#0a1628'),
        ]),
    ]))
    story.append(tbl)

    story.append(Spacer(1, 6*mm))
    story.append(HRFlowable(width="100%", thickness=0.4,
                             color=colors.HexColor('#1e3a5f'), spaceAfter=4))
    story.append(Paragraph(
        "This document was generated by DocAI using AI transcription and is intended "
        "for clinical reference only. Please verify all information with the treating physician.",
        s['disclaimer'],
    ))

    doc.build(story)


# Public API

def generate_pdf(doc):
    """ClinicalDocument -> raw PDF bytes."""
    try:
        doctor = doc.transcript.audio.doctor
        doctor_name = f"Dr. {doctor.get_full_name() or doctor.username}"
    except Exception:
        doctor_name = "Doctor"

    buf = io.BytesIO()
    _build_premium_pdf(
        buffer=buf,
        patient_name=doc.patient_name or "Unknown Patient",
        record_id=doc.pk,
        created_at=doc.created_at,
        doctor_name=doctor_name,
        fields={
            "Chief Complaint": doc.chief_complaint,
            "History":         doc.history,
            "Examination":     doc.examination,
            "Diagnosis":       doc.diagnosis,
            "Prescription":    doc.prescription,
            "Treatment Plan":  doc.treatment_plan,
            "Follow Up":       doc.follow_up,
        },
    )
    buf.seek(0)
    return buf.read()


def export_transcription_pdf(transcription, user=None):
    """Transcription -> HttpResponse PDF download."""
    if user:
        doctor_name = f"Dr. {user.get_full_name() or user.username}"
    else:
        doctor_name = "Doctor"

    buf = io.BytesIO()
    _build_premium_pdf(
        buffer=buf,
        patient_name=transcription.patient_name or "Unknown Patient",
        record_id=transcription.id,
        created_at=transcription.created_at,
        doctor_name=doctor_name,
        fields={
            "Chief Complaint":      transcription.chief_complaint,
            "Present Illness":      transcription.present_illness,
            "Diagnosis":            transcription.diagnosis,
            "Prescription":         transcription.prescription,
            "Treatment Plan":       transcription.treatment_plan,
            "Follow Up":            transcription.follow_up,
            "Vitals":               transcription.vitals,
            "Past Medical History": transcription.past_medical_history,
        },
    )
    buf.seek(0)

    patient  = (transcription.patient_name or "patient").replace(" ", "_").lower()
    date_str = transcription.created_at.strftime("%Y%m%d")
    filename = f"DocAI_{patient}_{date_str}_{transcription.id:05d}.pdf"
    response = HttpResponse(buf, content_type="application/pdf")
    response["Content-Disposition"] = f'attachment; filename="{filename}"'
    return response